#!/bin/python3
import subprocess

cmd = ['sh', '-c', "upower -d | grep \"native-path\" && upower -d | grep \"percentage\""]
output = subprocess.check_output(cmd).decode().strip().split()
avg = round(float(output[-1][:-1]), 2)
print(avg)
# print(f"{output}")
