#!/bin/python3
import os
import subprocess
from pathlib import Path


if os.path.isdir('/sys/class/power_supply/BAT0') & os.path.isdir('/sys/class/power_supply/BAT1'):
    cmd = ['sh', '-c', "upower -d | grep \"native-path\" && upower -d | grep \"percentage\""]
    output = subprocess.check_output(cmd).decode().strip().split()
    # cmd = ['sh', '-c', f"{Path.home()}/.local/share/scripts/dual_batteries"]
    # output = subprocess.check_output(cmd).decode().strip().split()
    print(f"1:{output[-1]} - 2:{output[-3]} ()")
else:
    print("Desktop")
