#!/bin/bash

WEBCAM="/dev/video1"

v4l2-ctl -d $WEBCAM --set-ctrl brightness="128"
v4l2-ctl -d $WEBCAM --set-ctrl contrast="128"
v4l2-ctl -d $WEBCAM --set-ctrl saturation="128"
v4l2-ctl -d $WEBCAM --set-ctrl gain="150"
v4l2-ctl -d $WEBCAM --set-ctrl auto_exposure="1"
v4l2-ctl -d $WEBCAM --set-ctrl exposure_time_absolute="300"
v4l2-ctl -d $WEBCAM --set-ctrl focus_automatic_continuous="1"
v4l2-ctl -d $WEBCAM --set-ctrl zoom_absolute="100"
