#!/bin/bash

# For linking my dots on my Macbook

ln -sf ~/Documents/Code/dotfiles/.config/doom/ ~/.config
ln -sf ~/Documents/Code/dotfiles/.config/kitty ~/.config
ln -sf ~/Documents/Code/dotfiles/.config/mpv/ ~/.config
ln -sf ~/Documents/Code/dotfiles/.config/nvim/ ~/.config
ln -sf ~/Documents/Code/dotfiles/.config/tmux/ ~/.config
ln -sf ~/Documents/Code/dotfiles/.config/zathura/ ~/.config
ln -sf ~/Documents/Code/dotfiles/.config/zsh ~/.config

ln -sf ~/Documents/Code/dotfiles/.config/aerospace ~/.config

ln -sf ~/Documents/Code/dotfiles/.local/share/scripts/ ~/.local/share

ln -s ~/Documents/Code/dotfiles/.zshenv ~/
