#!/usr/bin/env bash

cd $(tmux run "echo #{pane_start_path}")
url=$(git remote get-url origin)

if [[ $url == *github.com* ]]; then
  if [[ $url == git@* ]]; then
    url="${url#git@}"
    url="${url/:/\/}"
    url="http://$url"
  fi
  # Determine whether it's on Mac or Linux
  if [[ $OSTYPE == 'darwin'* ]]; then
    # You can't run "/Applications/Google\ Chrome.app" like on Linux
    open -a "Google Chrome" $url
  else
    "google-chrome" $url
  fi
else
  echo "this repo is not hosted on github"
fi

