[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[window]
padding = { x = 10, y = 10 }

[env]
WINIT_X11_SCALE_FACTOR = '1.0'
TERM = "xterm-256color"

[font]
normal = { family = 'IosevkaTerm Nerd Font' }
size = 15
